import Foundation

struct DesignTokenSavedConfig: Identifiable, Equatable {
    let url: URL
    let savedAt: Date

    var id: String { url.lastPathComponent }
    var displayName: String { url.deletingPathExtension().lastPathComponent }
}

struct DesignTokenWriter {
    private static let sourceFileURL = URL(fileURLWithPath: #filePath)

    private let encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        return encoder
    }()

    private let decoder = JSONDecoder()

    func workspaceDirectory() -> URL {
        var repositoryRoot = Self.sourceFileURL
        for _ in 0..<5 {
            repositoryRoot.deleteLastPathComponent()
        }

        return repositoryRoot
            .deletingLastPathComponent()
            .appendingPathComponent("_fantastic_island_design_tool", isDirectory: true)
    }

    func snapshotsDirectory() -> URL {
        workspaceDirectory().appendingPathComponent("snapshots", isDirectory: true)
    }

    @discardableResult
    func write(tokens: IslandDesignTokens) throws -> URL {
        let directory = workspaceDirectory()
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: snapshotsDirectory(), withIntermediateDirectories: true)

        let jsonURL = directory.appendingPathComponent("working_tokens.json")
        let data = try encoder.encode(tokens)
        try data.write(to: jsonURL, options: .atomic)

        let manifestURL = directory.appendingPathComponent("working_tokens.swift")
        try renderSwiftSnapshot(tokens).write(to: manifestURL, atomically: true, encoding: .utf8)

        let snapshotURL = snapshotsDirectory().appendingPathComponent(snapshotFileName(for: Date()))
        try data.write(to: snapshotURL, options: .atomic)
        return directory
    }

    func listSavedConfigs() -> [DesignTokenSavedConfig] {
        guard let urls = try? FileManager.default.contentsOfDirectory(
            at: snapshotsDirectory(),
            includingPropertiesForKeys: [.contentModificationDateKey],
            options: [.skipsHiddenFiles]
        ) else {
            return []
        }

        return urls
            .filter { $0.pathExtension == "json" }
            .compactMap { url in
                let values = try? url.resourceValues(forKeys: [.contentModificationDateKey])
                let savedAt = values?.contentModificationDate ?? .distantPast
                return DesignTokenSavedConfig(url: url, savedAt: savedAt)
            }
            .sorted { $0.savedAt > $1.savedAt }
    }

    func loadSavedConfig(_ config: DesignTokenSavedConfig) throws -> IslandDesignTokens {
        let data = try Data(contentsOf: config.url)
        return try decoder.decode(IslandDesignTokens.self, from: data)
    }

    private func snapshotFileName(for date: Date) -> String {
        let formatter = DateFormatter()
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone.current
        formatter.dateFormat = "yyyy-MM-dd_HH-mm-ss"
        return "tokens_\(formatter.string(from: date)).json"
    }

    private func renderSwiftSnapshot(_ tokens: IslandDesignTokens) -> String {
        """
        import Foundation

        // Generated by Fantastic Island Design Token Editor.
        // This file is an external debug snapshot and is not compiled into the app target.

        let islandDesignTokenSnapshotJSON = \"""
        \(String(data: (try? encoder.encode(tokens)) ?? Data(), encoding: .utf8) ?? "{}")
        \"""
        """
    }
}
